# Generated by Django 4.2.3 on 2023-07-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('link', models.CharField(max_length=200)),
                ('importance', models.IntegerField(default=3)),
            ],
            options={
                'ordering': ['-importance', '-date'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('authors', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=4)),
                ('link', models.CharField(max_length=100)),
                ('journal', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('cwp', 'conference and workshop proceedings'), ('prp', 'peer reviewed journal papers'), ('sp', 'selected papers')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=200)),
                ('mail', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=1000)),
                ('google_scholar', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.CharField(choices=[('prof', 'professor'), ('phd', 'phd'), ('ms', 'master'), ('ug', 'undergraduate'), ('al.phd', 'alumni phd'), ('al.ms', 'alumni master'), ('al.ug', 'alumni undergraduate')], max_length=8)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('leader', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=200)),
                ('mail', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=1000)),
                ('google_scholar', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.CharField(choices=[('prof', 'professor'), ('phd', 'phd'), ('ms', 'master'), ('ug', 'undergraduate'), ('al.phd', 'alumni phd'), ('al.ms', 'alumni master'), ('al.ug', 'alumni undergraduate')], max_length=8)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
